CREATE TABLE MESSAGES(
    ID INT,
    CONSTRAINT MESSAGE_PK PRIMARY KEY (ID),
    TEXT TEXT,
    DATE_SENT TIMESTAMP,
    DATE_READ TIMESTAMP,
    USER_FROM_ID INT,
    CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS(ID),
    USER_TO_ID INT,
    CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS(ID)
);