CREATE TABLE USERS(
    ID INT,
    CONSTRAINT USER_PK PRIMARY KEY (ID),
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    EMAIL VARCHAR(30) UNIQUE NOT NULL,
    COUNTRY VARCHAR(20),
    TOWN VARCHAR(20),
    AGE SMALLINT,
    DATE_REGISTERED TIMESTAMP,
    DATE_LAST_ACTIVE TIMESTAMP,
    RELATIONSHIP_STATUS VARCHAR(20),
    RELIGION VARCHAR(15),
    SCHOOL VARCHAR(20),
    UNIVERSITY VARCHAR(20)
);