CREATE TABLE RELATIONSHIPS(
    USER_FROM_ID INT,
    USER_TO_ID INT,
    CONSTRAINT RELATIONSHIP_PK PRIMARY KEY (USER_FROM_ID, USER_TO_ID),
    STATUS VARCHAR(30),
    START_OF_RLT TIMESTAMP,
    CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS (ID),
    CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS (ID)
);