CREATE TABLE RELATIONSHIPS(
    USER_FROM_ID INT NOT NULL,
    USER_TO_ID INT NOT NULL,
    CONSTRAINT RELATIONSHIP_PK PRIMARY KEY (USER_FROM_ID, USER_TO_ID)
    STATUS VARCHAR(30),
    START_OF_RLT TIMESTAMP
);