CREATE TABLE MESSAGES(
    ID NUMBER,
    CONSTRAINT MESSAGE_PK PRIMARY KEY (ID),
    TEXT CLOB,
    DATE_SENT DATE,
    DATE_READ DATE,
    USER_FROM_ID NUMBER,
    CONSTRAINT USER_FROM_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS(ID),
    USER_TO_ID NUMBER,
    CONSTRAINT USER_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS(ID)
);