CREATE TABLE TAGS(
    POST_ID INT,
    CONSTRAINT POST_FK FOREIGN KEY (POST_ID) REFERENCES POSTS(ID),
    USER_ID INT,
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT TAG_PK PRIMARY KEY (POST_ID, USER_ID)
);