CREATE TABLE POSTS(
    ID INT,
    CONSTRAINT POST_PK PRIMARY KEY (ID),
    MESSAGE TEXT,
    DATE_POSTED TIMESTAMP,
    LOCATION VARCHAR(30),
    USER_POSTED_ID INT,
    CONSTRAINT USER_POSTED_FK FOREIGN KEY (USER_POSTED_ID) REFERENCES USERS(ID),
    USER_PAGE_ID INT,
    CONSTRAINT USER_PAGE_FK FOREIGN KEY (USER_PAGE_ID) REFERENCES USERS(ID)
);