CREATE TABLE USERS(
    ID NUMBER,
    CONSTRAINT USER_PK PRIMARY KEY (ID),
    FIRST_NAME NVARCHAR2(30),
    LAST_NAME NVARCHAR2(30),
    PHONE NVARCHAR2(15),
    COUNTRY NVARCHAR2(20),
    TOWN NVARCHAR2(20),
    AGE NUMBER(3,0),
    DATE_REGISTERED DATE,
    DATE_LAST_ACTIVE DATE,
    RELATIONSHIP_STATUS NVARCHAR2(20),
    RELIGION NVARCHAR2(15),
    SCHOOL NVARCHAR2(20),
    UNIVERSITY NVARCHAR2(20)
);